apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto-ikasenpresa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proyecto-ikasenpresa
  template:
    metadata:
      labels:
        app: proyecto-ikasenpresa
    spec:
      containers:
        - name: proyecto-ikasenpresa
          image: kratosmessi1/proyeco_ikasenpresa:1.0.0-30
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
