apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto-ikasenpresa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proyecto-ikasenpresa
  template:
    metadata:
      labels:
        app: proyecto-ikasenpresa
    spec:
      containers:
        - name: proyecto-ikasenpresa
          image: https://hub.docker.com/repository/docker/kratosmessi1/proyeco_ikasenpresa/tags/1.0.0-22
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-secret

