apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto_ikasenpresa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proyecto_ikasenpresa
  template:
    metadata:
      labels:
        app: proyecto_ikasenpresa
    spec:
      containers:
        - name: proyecto_ikasenpresa
          image: kratosmessi1/proyecto_ikasenpresa:1.0.0-22
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
